name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

permissions:
  deployments: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print job's parameter values
        run: echo "${{ toJSON(inputs) }}"
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '>=18.15'
      - name: Build dependencies
        run: npm ci && npm run build

      - name: Deploy to development
        if: ${{ inputs.environment == 'development' }}
        run: npm run deploy:dev

      - name: Deploy to staging
        if: ${{ inputs.environment == 'staging' }}
        run: npm run deploy:staging

      - name: Deploy to production
        if: ${{ inputs.environment == 'production' }}
        run: npm run deploy:prod
